### ISSUE TITLE
Campaign: Menu

### ISSUE THREAD

**Issue by svenseeberg** [verdigado/gruene_app#185]
**As an app user, I want to be able to navigate between campaigning sub-sections in order to participate in these, inform myself about the current status of the campaign and where possible gather insights by comparing the modi / layers.**

Acceptance criteria:
- [x] The Door(Haustür) sub-menu is shown per default
- [x] App users can choose the sub-menu to be displayed (Doors, Posters, etc.)
- [x] 1st position from left: "Haustür" links to #217, opens up  #268 , edited #338
- [x] 2nd position: "Plakate" links to #183, opens up #267 , edited #340
- [x] 3rd position: "Flyer" links to #218, opens up #266 , edited #342
- [x] 4th position: "Team" (no link, grey)
- [x] 5th position: "Statistik" (no link, grey)

Further information:
- "Team" #179 
- "Statistik" #178 #196 
- "Standortsuche" 🔍 #216 
- #260 

Design:
When the campaign icon "_Wahlkampf_" is clicked in the main menu, the submenu campaigning appears for all subpages.
The selected menu item has a green underlining.

The menu items "Haustür", "Plakate" and "Flyer" have a 2nd submenu line.
<img width="259" alt="361197216-aa219216-7661-4e71-80a4-3fae6535f569" src="https://github.com/user-attachments/assets/c0711568-9984-4b76-9ca3-ed51a377edc8">

<img width="324" alt="Bildschirmfoto 2024-11-03 um 13 51 45" src="https://github.com/user-attachments/assets/c5095a45-f251-44f9-8ded-07d2da4f563d">
<img width="312" alt="Bildschirmfoto 2024-11-03 um 13 51 54" src="https://github.com/user-attachments/assets/bc973e71-bc33-4b1e-8274-b0856cd9710b">
<img width="310" alt="Bildschirmfoto 2024-11-03 um 13 52 04" src="https://github.com/user-attachments/assets/d4bebde2-40f3-4940-b080-6b5293d0d98f">

Prototype:
https://www.figma.com/proto/7wE0Iveas3GGb8u4oL0714/App-Design-Mitglieder-App-(1)-(Copy)?node-id=2654-4866&t=b8swD5IOAFfZ0OSo-1&starting-point-node-id=2425%3A17429

Pollion reference: https://github.com/pollion/sunflower-app/issues/20

**Comment by melegiul** [comment]
> Ist es sinnvoll auch keine Kategorie auswählen zu lassen, also alle drei Felder ohne Marker und dann nur die Karte anzuzeigen?

Ich würde sagen, dass immer mindestens eine Option ausgewählt bleibt. Ich kann mir nicht vorstellen, dass sich User*innen eine Karte ohne Kategorien wünschen.

Es sei denn, das UI zum Wechseln zwischen den Karten-Modi profitiert stark dadurch z.B. indem dadurch die Bedienung intuitiver/nutzer*innen-freundlicher wird. In dem Fall sehe ich keinen dringenden Grund, der dagegen spricht.

**Comment by nscharioth** [comment]
Pollion reference: https://github.com/pollion/sunflower-app/issues/20

**Comment by JuliaFreitagBGSt** [comment]
@nscharioth the idea of grouping all actions in a submenu item is great, but because of the new timeline we are gonna stick to the prototyp (one map, three layers, each layer with its own action-buttons/menu)

issue is reviewed

**Comment by nscharioth** [comment]
Issue edited to reflect Release 0*

@iantrieschmann @JuliaFreitagBGSt @leagerndt
